// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "C:/Users/gowth/Downloads/themeforest-Va4KCQY1-tairo-multipurpose-nuxt-tailwind-css-dashboard-system/.app/app.config";
import type { default as appConfig1 } from "C:/Users/gowth/Downloads/themeforest-Va4KCQY1-tairo-multipurpose-nuxt-tailwind-css-dashboard-system/layers/tairo/app.config";
import type { default as appConfig2 } from "C:/Users/gowth/Downloads/themeforest-Va4KCQY1-tairo-multipurpose-nuxt-tailwind-css-dashboard-system/node_modules/@shuriken-ui/nuxt/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1, typeof appConfig2]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}