
interface _GlobalComponents {
      'TairoLogo': typeof import("../../layers/tairo/components/global/TairoLogo.vue")['default']
    'TairoLogoText': typeof import("../../layers/tairo/components/global/TairoLogoText.vue")['default']
    'TairoToaster': typeof import("../../layers/tairo/components/global/TairoToaster.vue")['default']
    'TairoTocAnchor': typeof import("../../layers/tairo/components/global/TairoTocAnchor.vue")['default']
    'TairoCheckAnimated': typeof import("../../layers/tairo/components/TairoCheckAnimated.vue")['default']
    'TairoContentWrapper': typeof import("../../layers/tairo/components/TairoContentWrapper.vue")['default']
    'TairoContentWrapperTabbed': typeof import("../../layers/tairo/components/TairoContentWrapperTabbed.vue")['default']
    'TairoError': typeof import("../../layers/tairo/components/TairoError.vue")['default']
    'TairoFlexTable': typeof import("../../layers/tairo/components/TairoFlexTable.vue")['default']
    'TairoFlexTableCell': typeof import("../../layers/tairo/components/TairoFlexTableCell.vue")['default']
    'TairoFlexTableHeading': typeof import("../../layers/tairo/components/TairoFlexTableHeading.vue")['default']
    'TairoFlexTableRow': typeof import("../../layers/tairo/components/TairoFlexTableRow.vue")['default']
    'TairoFormGroup': typeof import("../../layers/tairo/components/TairoFormGroup.vue")['default']
    'TairoFormSave': typeof import("../../layers/tairo/components/TairoFormSave.vue")['default']
    'TairoImageZoom': typeof import("../../layers/tairo/components/TairoImageZoom.vue")['default']
    'TairoModal': typeof import("../../layers/tairo/components/TairoModal.vue")['default']
    'TairoPanels': typeof import("../../layers/tairo/components/TairoPanels.vue")['default']
    'TairoPasswordStrength': typeof import("../../layers/tairo/components/TairoPasswordStrength.vue")['default']
    'TairoPopover': typeof import("../../layers/tairo/components/TairoPopover.vue")['default']
    'TairoPopoverContentDual': typeof import("../../layers/tairo/components/TairoPopoverContentDual.vue")['default']
    'TairoPopoverContentHelp': typeof import("../../layers/tairo/components/TairoPopoverContentHelp.vue")['default']
    'TairoPopoverContentMedia': typeof import("../../layers/tairo/components/TairoPopoverContentMedia.vue")['default']
    'TairoTable': typeof import("../../layers/tairo/components/TairoTable.vue")['default']
    'TairoTableCell': typeof import("../../layers/tairo/components/TairoTableCell.vue")['default']
    'TairoTableHeading': typeof import("../../layers/tairo/components/TairoTableHeading.vue")['default']
    'TairoTableRow': typeof import("../../layers/tairo/components/TairoTableRow.vue")['default']
    'TairoToc': typeof import("../../layers/tairo/components/TairoToc.vue")['default']
    'TairoWelcome': typeof import("../../layers/tairo/components/TairoWelcome.vue")['default']
    'BaseAccordion': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseAccordion.vue")['default']
    'BaseAvatar': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseAvatar.vue")['default']
    'BaseAvatarGroup': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseAvatarGroup.vue")['default']
    'BaseBreadcrumb': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseBreadcrumb.vue")['default']
    'BaseButton': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButton.vue")['default']
    'BaseButtonAction': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonAction.vue")['default']
    'BaseButtonClose': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonClose.vue")['default']
    'BaseButtonGroup': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonGroup.vue")['default']
    'BaseButtonIcon': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonIcon.vue")['default']
    'BaseCard': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseCard.vue")['default']
    'BaseDropdown': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseDropdown.vue")['default']
    'BaseDropdownDivider': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseDropdownDivider.vue")['default']
    'BaseDropdownItem': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseDropdownItem.vue")['default']
    'BaseFocusLoop': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseFocusLoop.vue")['default']
    'BaseHeading': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseHeading.vue")['default']
    'BaseIconBox': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseIconBox.vue")['default']
    'BaseKbd': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseKbd.vue")['default']
    'BaseLink': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseLink.vue")['default']
    'BaseList': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseList.vue")['default']
    'BaseListItem': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseListItem.vue")['default']
    'BaseMessage': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseMessage.vue")['default']
    'BasePagination': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BasePagination.vue")['default']
    'BaseParagraph': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseParagraph.vue")['default']
    'BasePlaceholderPage': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BasePlaceholderPage.vue")['default']
    'BasePlaceload': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BasePlaceload.vue")['default']
    'BaseProgress': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseProgress.vue")['default']
    'BaseProgressCircle': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseProgressCircle.vue")['default']
    'BaseProse': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseProse.vue")['default']
    'BaseSnack': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseSnack.vue")['default']
    'BaseTabSlider': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseTabSlider.vue")['default']
    'BaseTabs': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseTabs.vue")['default']
    'BaseTag': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseTag.vue")['default']
    'BaseText': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseText.vue")['default']
    'BaseThemeSwitch': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseThemeSwitch.vue")['default']
    'BaseThemeToggle': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseThemeToggle.vue")['default']
    'IconCheck': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconCheck.vue")['default']
    'IconCheckCircle': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconCheckCircle.vue")['default']
    'IconChevronDown': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconChevronDown.vue")['default']
    'IconClose': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconClose.vue")['default']
    'IconIndeterminate': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconIndeterminate.vue")['default']
    'IconMinus': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconMinus.vue")['default']
    'IconMoon': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconMoon.vue")['default']
    'IconPlus': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconPlus.vue")['default']
    'IconSun': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconSun.vue")['default']
    'BaseAutocomplete': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseAutocomplete.vue")['default']
    'BaseAutocompleteItem': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseAutocompleteItem.vue")['default']
    'BaseCheckbox': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseCheckbox.vue")['default']
    'BaseCheckboxAnimated': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseCheckboxAnimated.vue")['default']
    'BaseCheckboxHeadless': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseCheckboxHeadless.vue")['default']
    'BaseFullscreenDropfile': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseFullscreenDropfile.vue")['default']
    'BaseInput': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInput.vue")['default']
    'BaseInputFile': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputFile.vue")['default']
    'BaseInputFileHeadless': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputFileHeadless.vue")['default']
    'BaseInputHelpText': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputHelpText.vue")['default']
    'BaseInputNumber': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputNumber.vue")['default']
    'BaseListbox': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseListbox.vue")['default']
    'BaseListboxItem': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseListboxItem.vue")['default']
    'BaseRadio': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseRadio.vue")['default']
    'BaseRadioHeadless': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseRadioHeadless.vue")['default']
    'BaseSelect': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseSelect.vue")['default']
    'BaseSwitchBall': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseSwitchBall.vue")['default']
    'BaseSwitchThin': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseSwitchThin.vue")['default']
    'BaseTextarea': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseTextarea.vue")['default']
    'BaseTreeSelect': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseTreeSelect.vue")['default']
    'BaseTreeSelectItem': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseTreeSelectItem.vue")['default']
    'NuxtWelcome': typeof import("../../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'ColorScheme': typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'Icon': typeof import("../../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyTairoLogo': typeof import("../../layers/tairo/components/global/TairoLogo.vue")['default']
    'LazyTairoLogoText': typeof import("../../layers/tairo/components/global/TairoLogoText.vue")['default']
    'LazyTairoToaster': typeof import("../../layers/tairo/components/global/TairoToaster.vue")['default']
    'LazyTairoTocAnchor': typeof import("../../layers/tairo/components/global/TairoTocAnchor.vue")['default']
    'LazyTairoCheckAnimated': typeof import("../../layers/tairo/components/TairoCheckAnimated.vue")['default']
    'LazyTairoContentWrapper': typeof import("../../layers/tairo/components/TairoContentWrapper.vue")['default']
    'LazyTairoContentWrapperTabbed': typeof import("../../layers/tairo/components/TairoContentWrapperTabbed.vue")['default']
    'LazyTairoError': typeof import("../../layers/tairo/components/TairoError.vue")['default']
    'LazyTairoFlexTable': typeof import("../../layers/tairo/components/TairoFlexTable.vue")['default']
    'LazyTairoFlexTableCell': typeof import("../../layers/tairo/components/TairoFlexTableCell.vue")['default']
    'LazyTairoFlexTableHeading': typeof import("../../layers/tairo/components/TairoFlexTableHeading.vue")['default']
    'LazyTairoFlexTableRow': typeof import("../../layers/tairo/components/TairoFlexTableRow.vue")['default']
    'LazyTairoFormGroup': typeof import("../../layers/tairo/components/TairoFormGroup.vue")['default']
    'LazyTairoFormSave': typeof import("../../layers/tairo/components/TairoFormSave.vue")['default']
    'LazyTairoImageZoom': typeof import("../../layers/tairo/components/TairoImageZoom.vue")['default']
    'LazyTairoModal': typeof import("../../layers/tairo/components/TairoModal.vue")['default']
    'LazyTairoPanels': typeof import("../../layers/tairo/components/TairoPanels.vue")['default']
    'LazyTairoPasswordStrength': typeof import("../../layers/tairo/components/TairoPasswordStrength.vue")['default']
    'LazyTairoPopover': typeof import("../../layers/tairo/components/TairoPopover.vue")['default']
    'LazyTairoPopoverContentDual': typeof import("../../layers/tairo/components/TairoPopoverContentDual.vue")['default']
    'LazyTairoPopoverContentHelp': typeof import("../../layers/tairo/components/TairoPopoverContentHelp.vue")['default']
    'LazyTairoPopoverContentMedia': typeof import("../../layers/tairo/components/TairoPopoverContentMedia.vue")['default']
    'LazyTairoTable': typeof import("../../layers/tairo/components/TairoTable.vue")['default']
    'LazyTairoTableCell': typeof import("../../layers/tairo/components/TairoTableCell.vue")['default']
    'LazyTairoTableHeading': typeof import("../../layers/tairo/components/TairoTableHeading.vue")['default']
    'LazyTairoTableRow': typeof import("../../layers/tairo/components/TairoTableRow.vue")['default']
    'LazyTairoToc': typeof import("../../layers/tairo/components/TairoToc.vue")['default']
    'LazyTairoWelcome': typeof import("../../layers/tairo/components/TairoWelcome.vue")['default']
    'LazyBaseAccordion': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseAccordion.vue")['default']
    'LazyBaseAvatar': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseAvatar.vue")['default']
    'LazyBaseAvatarGroup': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseAvatarGroup.vue")['default']
    'LazyBaseBreadcrumb': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseBreadcrumb.vue")['default']
    'LazyBaseButton': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButton.vue")['default']
    'LazyBaseButtonAction': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonAction.vue")['default']
    'LazyBaseButtonClose': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonClose.vue")['default']
    'LazyBaseButtonGroup': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonGroup.vue")['default']
    'LazyBaseButtonIcon': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonIcon.vue")['default']
    'LazyBaseCard': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseCard.vue")['default']
    'LazyBaseDropdown': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseDropdown.vue")['default']
    'LazyBaseDropdownDivider': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseDropdownDivider.vue")['default']
    'LazyBaseDropdownItem': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseDropdownItem.vue")['default']
    'LazyBaseFocusLoop': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseFocusLoop.vue")['default']
    'LazyBaseHeading': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseHeading.vue")['default']
    'LazyBaseIconBox': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseIconBox.vue")['default']
    'LazyBaseKbd': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseKbd.vue")['default']
    'LazyBaseLink': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseLink.vue")['default']
    'LazyBaseList': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseList.vue")['default']
    'LazyBaseListItem': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseListItem.vue")['default']
    'LazyBaseMessage': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseMessage.vue")['default']
    'LazyBasePagination': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BasePagination.vue")['default']
    'LazyBaseParagraph': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseParagraph.vue")['default']
    'LazyBasePlaceholderPage': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BasePlaceholderPage.vue")['default']
    'LazyBasePlaceload': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BasePlaceload.vue")['default']
    'LazyBaseProgress': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseProgress.vue")['default']
    'LazyBaseProgressCircle': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseProgressCircle.vue")['default']
    'LazyBaseProse': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseProse.vue")['default']
    'LazyBaseSnack': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseSnack.vue")['default']
    'LazyBaseTabSlider': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseTabSlider.vue")['default']
    'LazyBaseTabs': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseTabs.vue")['default']
    'LazyBaseTag': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseTag.vue")['default']
    'LazyBaseText': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseText.vue")['default']
    'LazyBaseThemeSwitch': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseThemeSwitch.vue")['default']
    'LazyBaseThemeToggle': typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseThemeToggle.vue")['default']
    'LazyIconCheck': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconCheck.vue")['default']
    'LazyIconCheckCircle': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconCheckCircle.vue")['default']
    'LazyIconChevronDown': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconChevronDown.vue")['default']
    'LazyIconClose': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconClose.vue")['default']
    'LazyIconIndeterminate': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconIndeterminate.vue")['default']
    'LazyIconMinus': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconMinus.vue")['default']
    'LazyIconMoon': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconMoon.vue")['default']
    'LazyIconPlus': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconPlus.vue")['default']
    'LazyIconSun': typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconSun.vue")['default']
    'LazyBaseAutocomplete': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseAutocomplete.vue")['default']
    'LazyBaseAutocompleteItem': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseAutocompleteItem.vue")['default']
    'LazyBaseCheckbox': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseCheckbox.vue")['default']
    'LazyBaseCheckboxAnimated': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseCheckboxAnimated.vue")['default']
    'LazyBaseCheckboxHeadless': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseCheckboxHeadless.vue")['default']
    'LazyBaseFullscreenDropfile': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseFullscreenDropfile.vue")['default']
    'LazyBaseInput': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInput.vue")['default']
    'LazyBaseInputFile': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputFile.vue")['default']
    'LazyBaseInputFileHeadless': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputFileHeadless.vue")['default']
    'LazyBaseInputHelpText': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputHelpText.vue")['default']
    'LazyBaseInputNumber': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputNumber.vue")['default']
    'LazyBaseListbox': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseListbox.vue")['default']
    'LazyBaseListboxItem': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseListboxItem.vue")['default']
    'LazyBaseRadio': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseRadio.vue")['default']
    'LazyBaseRadioHeadless': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseRadioHeadless.vue")['default']
    'LazyBaseSelect': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseSelect.vue")['default']
    'LazyBaseSwitchBall': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseSwitchBall.vue")['default']
    'LazyBaseSwitchThin': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseSwitchThin.vue")['default']
    'LazyBaseTextarea': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseTextarea.vue")['default']
    'LazyBaseTreeSelect': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseTreeSelect.vue")['default']
    'LazyBaseTreeSelectItem': typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseTreeSelectItem.vue")['default']
    'LazyNuxtWelcome': typeof import("../../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyColorScheme': typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyIcon': typeof import("../../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyNuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const TairoLogo: typeof import("../../layers/tairo/components/global/TairoLogo.vue")['default']
export const TairoLogoText: typeof import("../../layers/tairo/components/global/TairoLogoText.vue")['default']
export const TairoToaster: typeof import("../../layers/tairo/components/global/TairoToaster.vue")['default']
export const TairoTocAnchor: typeof import("../../layers/tairo/components/global/TairoTocAnchor.vue")['default']
export const TairoCheckAnimated: typeof import("../../layers/tairo/components/TairoCheckAnimated.vue")['default']
export const TairoContentWrapper: typeof import("../../layers/tairo/components/TairoContentWrapper.vue")['default']
export const TairoContentWrapperTabbed: typeof import("../../layers/tairo/components/TairoContentWrapperTabbed.vue")['default']
export const TairoError: typeof import("../../layers/tairo/components/TairoError.vue")['default']
export const TairoFlexTable: typeof import("../../layers/tairo/components/TairoFlexTable.vue")['default']
export const TairoFlexTableCell: typeof import("../../layers/tairo/components/TairoFlexTableCell.vue")['default']
export const TairoFlexTableHeading: typeof import("../../layers/tairo/components/TairoFlexTableHeading.vue")['default']
export const TairoFlexTableRow: typeof import("../../layers/tairo/components/TairoFlexTableRow.vue")['default']
export const TairoFormGroup: typeof import("../../layers/tairo/components/TairoFormGroup.vue")['default']
export const TairoFormSave: typeof import("../../layers/tairo/components/TairoFormSave.vue")['default']
export const TairoImageZoom: typeof import("../../layers/tairo/components/TairoImageZoom.vue")['default']
export const TairoModal: typeof import("../../layers/tairo/components/TairoModal.vue")['default']
export const TairoPanels: typeof import("../../layers/tairo/components/TairoPanels.vue")['default']
export const TairoPasswordStrength: typeof import("../../layers/tairo/components/TairoPasswordStrength.vue")['default']
export const TairoPopover: typeof import("../../layers/tairo/components/TairoPopover.vue")['default']
export const TairoPopoverContentDual: typeof import("../../layers/tairo/components/TairoPopoverContentDual.vue")['default']
export const TairoPopoverContentHelp: typeof import("../../layers/tairo/components/TairoPopoverContentHelp.vue")['default']
export const TairoPopoverContentMedia: typeof import("../../layers/tairo/components/TairoPopoverContentMedia.vue")['default']
export const TairoTable: typeof import("../../layers/tairo/components/TairoTable.vue")['default']
export const TairoTableCell: typeof import("../../layers/tairo/components/TairoTableCell.vue")['default']
export const TairoTableHeading: typeof import("../../layers/tairo/components/TairoTableHeading.vue")['default']
export const TairoTableRow: typeof import("../../layers/tairo/components/TairoTableRow.vue")['default']
export const TairoToc: typeof import("../../layers/tairo/components/TairoToc.vue")['default']
export const TairoWelcome: typeof import("../../layers/tairo/components/TairoWelcome.vue")['default']
export const BaseAccordion: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseAccordion.vue")['default']
export const BaseAvatar: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseAvatar.vue")['default']
export const BaseAvatarGroup: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseAvatarGroup.vue")['default']
export const BaseBreadcrumb: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseBreadcrumb.vue")['default']
export const BaseButton: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButton.vue")['default']
export const BaseButtonAction: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonAction.vue")['default']
export const BaseButtonClose: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonClose.vue")['default']
export const BaseButtonGroup: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonGroup.vue")['default']
export const BaseButtonIcon: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonIcon.vue")['default']
export const BaseCard: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseCard.vue")['default']
export const BaseDropdown: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseDropdown.vue")['default']
export const BaseDropdownDivider: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseDropdownDivider.vue")['default']
export const BaseDropdownItem: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseDropdownItem.vue")['default']
export const BaseFocusLoop: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseFocusLoop.vue")['default']
export const BaseHeading: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseHeading.vue")['default']
export const BaseIconBox: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseIconBox.vue")['default']
export const BaseKbd: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseKbd.vue")['default']
export const BaseLink: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseLink.vue")['default']
export const BaseList: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseList.vue")['default']
export const BaseListItem: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseListItem.vue")['default']
export const BaseMessage: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseMessage.vue")['default']
export const BasePagination: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BasePagination.vue")['default']
export const BaseParagraph: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseParagraph.vue")['default']
export const BasePlaceholderPage: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BasePlaceholderPage.vue")['default']
export const BasePlaceload: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BasePlaceload.vue")['default']
export const BaseProgress: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseProgress.vue")['default']
export const BaseProgressCircle: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseProgressCircle.vue")['default']
export const BaseProse: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseProse.vue")['default']
export const BaseSnack: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseSnack.vue")['default']
export const BaseTabSlider: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseTabSlider.vue")['default']
export const BaseTabs: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseTabs.vue")['default']
export const BaseTag: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseTag.vue")['default']
export const BaseText: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseText.vue")['default']
export const BaseThemeSwitch: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseThemeSwitch.vue")['default']
export const BaseThemeToggle: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseThemeToggle.vue")['default']
export const IconCheck: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconCheck.vue")['default']
export const IconCheckCircle: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconCheckCircle.vue")['default']
export const IconChevronDown: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconChevronDown.vue")['default']
export const IconClose: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconClose.vue")['default']
export const IconIndeterminate: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconIndeterminate.vue")['default']
export const IconMinus: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconMinus.vue")['default']
export const IconMoon: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconMoon.vue")['default']
export const IconPlus: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconPlus.vue")['default']
export const IconSun: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconSun.vue")['default']
export const BaseAutocomplete: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseAutocomplete.vue")['default']
export const BaseAutocompleteItem: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseAutocompleteItem.vue")['default']
export const BaseCheckbox: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseCheckbox.vue")['default']
export const BaseCheckboxAnimated: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseCheckboxAnimated.vue")['default']
export const BaseCheckboxHeadless: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseCheckboxHeadless.vue")['default']
export const BaseFullscreenDropfile: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseFullscreenDropfile.vue")['default']
export const BaseInput: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInput.vue")['default']
export const BaseInputFile: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputFile.vue")['default']
export const BaseInputFileHeadless: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputFileHeadless.vue")['default']
export const BaseInputHelpText: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputHelpText.vue")['default']
export const BaseInputNumber: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputNumber.vue")['default']
export const BaseListbox: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseListbox.vue")['default']
export const BaseListboxItem: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseListboxItem.vue")['default']
export const BaseRadio: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseRadio.vue")['default']
export const BaseRadioHeadless: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseRadioHeadless.vue")['default']
export const BaseSelect: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseSelect.vue")['default']
export const BaseSwitchBall: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseSwitchBall.vue")['default']
export const BaseSwitchThin: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseSwitchThin.vue")['default']
export const BaseTextarea: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseTextarea.vue")['default']
export const BaseTreeSelect: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseTreeSelect.vue")['default']
export const BaseTreeSelectItem: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseTreeSelectItem.vue")['default']
export const NuxtWelcome: typeof import("../../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ColorScheme: typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const Icon: typeof import("../../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyTairoLogo: typeof import("../../layers/tairo/components/global/TairoLogo.vue")['default']
export const LazyTairoLogoText: typeof import("../../layers/tairo/components/global/TairoLogoText.vue")['default']
export const LazyTairoToaster: typeof import("../../layers/tairo/components/global/TairoToaster.vue")['default']
export const LazyTairoTocAnchor: typeof import("../../layers/tairo/components/global/TairoTocAnchor.vue")['default']
export const LazyTairoCheckAnimated: typeof import("../../layers/tairo/components/TairoCheckAnimated.vue")['default']
export const LazyTairoContentWrapper: typeof import("../../layers/tairo/components/TairoContentWrapper.vue")['default']
export const LazyTairoContentWrapperTabbed: typeof import("../../layers/tairo/components/TairoContentWrapperTabbed.vue")['default']
export const LazyTairoError: typeof import("../../layers/tairo/components/TairoError.vue")['default']
export const LazyTairoFlexTable: typeof import("../../layers/tairo/components/TairoFlexTable.vue")['default']
export const LazyTairoFlexTableCell: typeof import("../../layers/tairo/components/TairoFlexTableCell.vue")['default']
export const LazyTairoFlexTableHeading: typeof import("../../layers/tairo/components/TairoFlexTableHeading.vue")['default']
export const LazyTairoFlexTableRow: typeof import("../../layers/tairo/components/TairoFlexTableRow.vue")['default']
export const LazyTairoFormGroup: typeof import("../../layers/tairo/components/TairoFormGroup.vue")['default']
export const LazyTairoFormSave: typeof import("../../layers/tairo/components/TairoFormSave.vue")['default']
export const LazyTairoImageZoom: typeof import("../../layers/tairo/components/TairoImageZoom.vue")['default']
export const LazyTairoModal: typeof import("../../layers/tairo/components/TairoModal.vue")['default']
export const LazyTairoPanels: typeof import("../../layers/tairo/components/TairoPanels.vue")['default']
export const LazyTairoPasswordStrength: typeof import("../../layers/tairo/components/TairoPasswordStrength.vue")['default']
export const LazyTairoPopover: typeof import("../../layers/tairo/components/TairoPopover.vue")['default']
export const LazyTairoPopoverContentDual: typeof import("../../layers/tairo/components/TairoPopoverContentDual.vue")['default']
export const LazyTairoPopoverContentHelp: typeof import("../../layers/tairo/components/TairoPopoverContentHelp.vue")['default']
export const LazyTairoPopoverContentMedia: typeof import("../../layers/tairo/components/TairoPopoverContentMedia.vue")['default']
export const LazyTairoTable: typeof import("../../layers/tairo/components/TairoTable.vue")['default']
export const LazyTairoTableCell: typeof import("../../layers/tairo/components/TairoTableCell.vue")['default']
export const LazyTairoTableHeading: typeof import("../../layers/tairo/components/TairoTableHeading.vue")['default']
export const LazyTairoTableRow: typeof import("../../layers/tairo/components/TairoTableRow.vue")['default']
export const LazyTairoToc: typeof import("../../layers/tairo/components/TairoToc.vue")['default']
export const LazyTairoWelcome: typeof import("../../layers/tairo/components/TairoWelcome.vue")['default']
export const LazyBaseAccordion: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseAccordion.vue")['default']
export const LazyBaseAvatar: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseAvatar.vue")['default']
export const LazyBaseAvatarGroup: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseAvatarGroup.vue")['default']
export const LazyBaseBreadcrumb: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseBreadcrumb.vue")['default']
export const LazyBaseButton: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButton.vue")['default']
export const LazyBaseButtonAction: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonAction.vue")['default']
export const LazyBaseButtonClose: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonClose.vue")['default']
export const LazyBaseButtonGroup: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonGroup.vue")['default']
export const LazyBaseButtonIcon: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseButtonIcon.vue")['default']
export const LazyBaseCard: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseCard.vue")['default']
export const LazyBaseDropdown: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseDropdown.vue")['default']
export const LazyBaseDropdownDivider: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseDropdownDivider.vue")['default']
export const LazyBaseDropdownItem: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseDropdownItem.vue")['default']
export const LazyBaseFocusLoop: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseFocusLoop.vue")['default']
export const LazyBaseHeading: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseHeading.vue")['default']
export const LazyBaseIconBox: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseIconBox.vue")['default']
export const LazyBaseKbd: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseKbd.vue")['default']
export const LazyBaseLink: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseLink.vue")['default']
export const LazyBaseList: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseList.vue")['default']
export const LazyBaseListItem: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseListItem.vue")['default']
export const LazyBaseMessage: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseMessage.vue")['default']
export const LazyBasePagination: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BasePagination.vue")['default']
export const LazyBaseParagraph: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseParagraph.vue")['default']
export const LazyBasePlaceholderPage: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BasePlaceholderPage.vue")['default']
export const LazyBasePlaceload: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BasePlaceload.vue")['default']
export const LazyBaseProgress: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseProgress.vue")['default']
export const LazyBaseProgressCircle: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseProgressCircle.vue")['default']
export const LazyBaseProse: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseProse.vue")['default']
export const LazyBaseSnack: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseSnack.vue")['default']
export const LazyBaseTabSlider: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseTabSlider.vue")['default']
export const LazyBaseTabs: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseTabs.vue")['default']
export const LazyBaseTag: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseTag.vue")['default']
export const LazyBaseText: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseText.vue")['default']
export const LazyBaseThemeSwitch: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseThemeSwitch.vue")['default']
export const LazyBaseThemeToggle: typeof import("../../node_modules/@shuriken-ui/nuxt/components/base/BaseThemeToggle.vue")['default']
export const LazyIconCheck: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconCheck.vue")['default']
export const LazyIconCheckCircle: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconCheckCircle.vue")['default']
export const LazyIconChevronDown: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconChevronDown.vue")['default']
export const LazyIconClose: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconClose.vue")['default']
export const LazyIconIndeterminate: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconIndeterminate.vue")['default']
export const LazyIconMinus: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconMinus.vue")['default']
export const LazyIconMoon: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconMoon.vue")['default']
export const LazyIconPlus: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconPlus.vue")['default']
export const LazyIconSun: typeof import("../../node_modules/@shuriken-ui/nuxt/components/icon/IconSun.vue")['default']
export const LazyBaseAutocomplete: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseAutocomplete.vue")['default']
export const LazyBaseAutocompleteItem: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseAutocompleteItem.vue")['default']
export const LazyBaseCheckbox: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseCheckbox.vue")['default']
export const LazyBaseCheckboxAnimated: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseCheckboxAnimated.vue")['default']
export const LazyBaseCheckboxHeadless: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseCheckboxHeadless.vue")['default']
export const LazyBaseFullscreenDropfile: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseFullscreenDropfile.vue")['default']
export const LazyBaseInput: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInput.vue")['default']
export const LazyBaseInputFile: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputFile.vue")['default']
export const LazyBaseInputFileHeadless: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputFileHeadless.vue")['default']
export const LazyBaseInputHelpText: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputHelpText.vue")['default']
export const LazyBaseInputNumber: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseInputNumber.vue")['default']
export const LazyBaseListbox: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseListbox.vue")['default']
export const LazyBaseListboxItem: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseListboxItem.vue")['default']
export const LazyBaseRadio: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseRadio.vue")['default']
export const LazyBaseRadioHeadless: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseRadioHeadless.vue")['default']
export const LazyBaseSelect: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseSelect.vue")['default']
export const LazyBaseSwitchBall: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseSwitchBall.vue")['default']
export const LazyBaseSwitchThin: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseSwitchThin.vue")['default']
export const LazyBaseTextarea: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseTextarea.vue")['default']
export const LazyBaseTreeSelect: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseTreeSelect.vue")['default']
export const LazyBaseTreeSelectItem: typeof import("../../node_modules/@shuriken-ui/nuxt/components/form/BaseTreeSelectItem.vue")['default']
export const LazyNuxtWelcome: typeof import("../../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyColorScheme: typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyIcon: typeof import("../../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyNuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
